script:
  - id: update_weather_icon
    then:
      - if:
          condition:
            lambda: |-
              return id(weather_condition_state).state == "sunny" &&
                     id(sun_state).state == "above_horizon";
          then:
            - lvgl.image.update:
                id: weather_icon
                src: weather_clear_day

      - if:
          condition:
            lambda: |-
              return id(weather_condition_state).state == "sunny" &&
                     id(sun_state).state == "below_horizon";
          then:
            - lvgl.image.update:
                id: weather_icon
                src: weather_clear_night

      - if:
          condition:
            lambda: |-
              return id(weather_condition_state).state == "clear-night";
          then:
            - lvgl.image.update:
                id: weather_icon
                src: weather_clear_night

      - if:
          condition:
            lambda: |-
              return id(weather_condition_state).state == "partlycloudy" &&
                     id(sun_state).state == "above_horizon";
          then:
            - lvgl.image.update:
                id: weather_icon
                src: weather_partly_cloudy_day

      - if:
          condition:
            lambda: |-
              return id(weather_condition_state).state == "partlycloudy" &&
                     id(sun_state).state == "below_horizon";
          then:
            - lvgl.image.update:
                id: weather_icon
                src: weather_partly_cloudy_night

      - if:
          condition:
            lambda: |-
              const std::string condition = id(weather_condition_state).state;
              return condition == "cloudy" || condition == "windy" ||
                     condition == "windy-variant" || condition == "exceptional" ||
                     condition == "unavailable" || condition == "unknown";
          then:
            - lvgl.image.update:
                id: weather_icon
                src: weather_cloudy

      - if:
          condition:
            lambda: |-
              const std::string condition = id(weather_condition_state).state;
              return condition == "rainy" || condition == "pouring" ||
                     condition == "hail";
          then:
            - lvgl.image.update:
                id: weather_icon
                src: weather_rain

      - if:
          condition:
            lambda: |-
              const std::string condition = id(weather_condition_state).state;
              return condition == "snowy" || condition == "snowy-rainy";
          then:
            - lvgl.image.update:
                id: weather_icon
                src: weather_snow

      - if:
          condition:
            lambda: |-
              return id(weather_condition_state).state == "fog";
          then:
            - lvgl.image.update:
                id: weather_icon
                src: weather_fog

      - if:
          condition:
            lambda: |-
              const std::string condition = id(weather_condition_state).state;
              return condition == "lightning" ||
                     condition == "lightning-rainy";
          then:
            - lvgl.image.update:
                id: weather_icon
                src: weather_thunderstorm

  - id: update_weather_background
    then:
      - if:
          condition:
            lambda: |-
              return id(weather_condition_state).state == "sunny" &&
                     id(sun_state).state == "above_horizon";
          then:
            - lvgl.image.update:
                id: ambient_background
                src: ambient_background_clear_day

      - if:
          condition:
            lambda: |-
              return id(weather_condition_state).state == "clear-night" ||
                     (id(weather_condition_state).state == "sunny" &&
                      id(sun_state).state == "below_horizon");
          then:
            - lvgl.image.update:
                id: ambient_background
                src: ambient_background_clear_night

      - if:
          condition:
            lambda: |-
              return id(weather_condition_state).state == "partlycloudy" &&
                     id(sun_state).state == "above_horizon";
          then:
            - lvgl.image.update:
                id: ambient_background
                src: ambient_background_partly_cloudy_day

      - if:
          condition:
            lambda: |-
              return id(weather_condition_state).state == "partlycloudy" &&
                     id(sun_state).state == "below_horizon";
          then:
            - lvgl.image.update:
                id: ambient_background
                src: ambient_background_partly_cloudy_night

      - if:
          condition:
            lambda: |-
              return id(weather_condition_state).state == "cloudy";
          then:
            - lvgl.image.update:
                id: ambient_background
                src: ambient_background_cloudy

      - if:
          condition:
            lambda: |-
              const std::string condition = id(weather_condition_state).state;
              return condition == "rainy" || condition == "pouring";
          then:
            - lvgl.image.update:
                id: ambient_background
                src: ambient_background_rain

      - if:
          condition:
            lambda: |-
              const std::string condition = id(weather_condition_state).state;
              return (condition == "snowy" || condition == "snowy-rainy") &&
                     id(sun_state).state == "above_horizon";
          then:
            - lvgl.image.update:
                id: ambient_background
                src: ambient_background_snowy_day

      - if:
          condition:
            lambda: |-
              const std::string condition = id(weather_condition_state).state;
              return (condition == "snowy" || condition == "snowy-rainy") &&
                     id(sun_state).state == "below_horizon";
          then:
            - lvgl.image.update:
                id: ambient_background
                src: ambient_background_snowy_night

      - if:
          condition:
            lambda: |-
              return id(weather_condition_state).state == "fog";
          then:
            - lvgl.image.update:
                id: ambient_background
                src: ambient_background_fog

      - if:
          condition:
            lambda: |-
              const std::string condition = id(weather_condition_state).state;
              return condition == "lightning" ||
                     condition == "lightning-rainy";
          then:
            - lvgl.image.update:
                id: ambient_background
                src: ambient_background_thunderstorm

text_sensor:
  - platform: homeassistant
    id: weather_condition_state
    entity_id: weather.toronto_forecast

    on_value:
      then:
        - lvgl.label.update:
            id: weather_condition
            text: !lambda |-
              if (x == "clear-night") return std::string("Clear Night");
              if (x == "sunny") return std::string("Sunny");
              if (x == "partlycloudy") return std::string("Partly Cloudy");
              if (x == "cloudy") return std::string("Cloudy");
              if (x == "fog") return std::string("Fog");
              if (x == "hail") return std::string("Hail");
              if (x == "lightning" || x == "lightning-rainy") {
                return std::string("Thunderstorm");
              }
              if (x == "pouring") return std::string("Heavy Rain");
              if (x == "rainy") return std::string("Rain");
              if (x == "snowy") return std::string("Snow");
              if (x == "snowy-rainy") return std::string("Sleet");
              if (x == "windy" || x == "windy-variant") {
                return std::string("Windy");
              }
              if (x == "exceptional") return std::string("Exceptional");
              if (x == "unavailable") return std::string("Unavailable");
              if (x == "unknown") return std::string("Unknown");

              return x;

        - script.execute: update_weather_icon
        - script.execute: update_weather_background

  - platform: homeassistant
    id: sun_state
    entity_id: sun.sun

    on_value:
      then:
        - script.execute: update_weather_icon
        - script.execute: update_weather_background

sensor:
  - platform: homeassistant
    id: weather_temperature_sensor
    entity_id: weather.toronto_forecast
    attribute: temperature

    on_value:
      then:
        - lvgl.label.update:
            id: weather_temperature
            text: !lambda |-
              char text[16];
              snprintf(text, sizeof(text), "%.0f°", x);
              return std::string(text);
